name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Create Release Artifact
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
      
      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0 # SDK version to use
      
      # Restore dependencies
      - name: Restore Dependencies
        run: dotnet restore WbfsFileSplitter/WbfsFileSplitter.csproj
      
      # Publish the application as a single executable
      - name: Publish Application
        run: dotnet publish WbfsFileSplitter/WbfsFileSplitter.csproj -c Release -r win-x64 -p:PublishSingleFile=true -o ./publish --self-contained true
      
      
      # Find and upload the single .exe file as an artifact
      - name: Upload Executable
        run: |
          $exeFile = Get-ChildItem -Path ./publish -Filter "*.exe" | Select-Object -First 1
          echo "Found executable: $($exeFile.FullName)"
          mv $exeFile.FullName ./WBFSFileSplitter.exe
        shell: pwsh

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: WBFSFileSplitter
          path: WBFSFileSplitter.exe